Repository naver/billboard.js, pull requests merged in 2019-12, with the labels that each got.

#1148 chore(dev-env): Update dependency
  package.json
  yarn.lock
Labels: dev-env

#1152 chore(dev-env): Update babel config
  .babelrc
  babel.config.js
Labels: dev-env

#1161 feat(grid): Intent to ship grid.focus.y
  demo/demo.js
  demo/simple-sidebar.css
  spec/internals/grid-spec.js
  src/api/api.flow.js
  src/api/api.tooltip.js
  src/config/Options.js
  src/config/classes.js
  src/interactions/interaction.js
  src/internals/ChartInternal.js
  src/internals/grid.js
  src/plugin/stanford/index.js
  src/scss/billboard.scss
  src/scss/theme/graph.scss
  src/scss/theme/insight.scss
  types/options.d.ts
Labels: feature

#1156 Use an HTTPS url for the gzip-size badge
  README.md
Labels: chore

#1165 feat(axis): Intent to ship axis.y2.tick.rotate
  spec/internals/axis-spec.js
  src/axis/Axis.js
  src/axis/AxisRenderer.js
  src/config/Options.js
  src/internals/size.js
  types/axis.d.ts
Labels: doc, feature

#1166 chore(dev-env): Update dependency
  package.json
  yarn.lock
Labels: chore

#1173 fix(arc): Fix handling spaced data name
  spec/interactions/interaction-spec.js
  src/interactions/interaction.js
  src/internals/color.js
Labels: bug

#1174 chore(dev-env): Update dependency
  package.json
  yarn.lock
Labels: dev-env

#1175 fix(line): Fix nullish data rendering with regions
  spec/internals/data-spec.js
  src/shape/line.js
Labels: bug

#1182 test(interaction): Update arc selector assertion
  spec/interactions/interaction-spec.js
Labels: test

#1183 chore(dev-env): Update dependency
  package.json
  yarn.lock
Labels: chore

#1187 chore(dev-env): Update dependency
  package.json
  yarn.lock
Labels: chore, dev-env
