Repository naver/billboard.js, pull requests merged in 2020-04, with the labels that each got.

#1300 fix(arc): Fix label text update w/threshold
  spec/assets/util.js
  spec/shape/shape.arc-spec.js
  src/shape/arc.js
Labels: bug

#1301 chore(dev-env): Add dpendabot config
  .dependabot/config.yml
  package.json
  yarn.lock
Labels: chore

#1304 fix(shape): Fix non-grouped area/bar to be drawn from bottom of x Axis
  spec/shape/shape.bar-spec.js
  spec/shape/shape.line-spec.js
  src/shape/bar.js
  src/shape/line.js
  src/shape/shape.js
Labels: bug

#1309 fix(grid): Fix possible error when grid.focus.show set false
  spec/interactions/interaction-spec.js
  src/internals/grid.js
Labels: bug

#1314 refactor(plugin): Remove the use of d3-array
  config/webpack.config.plugin.js
  package.json
  src/internals/util.js
  src/plugin/stanford/ColorScale.js
  src/plugin/stanford/index.js
  yarn.lock
Labels: refactoring

#1315 refactor(dev-env): Downgrade d3-scale to 2.x
  .dependabot/config.yml
  package.json
  yarn.lock
Labels: chore, dev-env

#1323 fix(shape): Fix incorrect area/bar rendering
  spec/shape/shape-spec.js
  src/shape/line.js
  src/shape/shape.js
Labels: bug

#1336 fix(shape): Correct stack step type rendering
  spec/shape/shape.line-spec.js
  src/data/data.js
  src/shape/shape.js
Labels: bug

#1339 chore(dev-env): Update dependencies
  package.json
  yarn.lock
Labels: chore

#1348 fix(core): Fix handling transition tasks
  spec/internals/core-spec.js
  src/internals/ChartInternal.js
  src/internals/grid.js
  src/internals/text.js
Labels: bug

#1360 chore(deps-dev): update dev dependency
  package.json
  yarn.lock
Labels: dev-env

#1361 chore: Use HTTPS for the homepage URL in package metadata
  package.json
Labels: chore

#1364 fix(tooltip): Fix tooltip rightest positioning
  spec/assets/common.css
  spec/internals/tooltip-spec.js
  src/internals/tooltip.js
Labels: bug

#1367 fix(data): Fix on determine grouped data
  .gitignore
  spec/shape/shape.line-spec.js
  src/data/data.js
  src/internals/tooltip.js
  src/shape/bar.js
Labels: bug
